AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation CI CD Stack for interactive

Parameters:
  ResourcePrefix:
    Description: Resource prefix that will be used for all resource names
    Type: String
    MinLength: "3"
    MaxLength: "12"
    AllowedPattern: "[a-z]+"
    Default: "interactive"
  EnvironmentName:
    Description: Environment name that will be used for resource names
    Type: String
    AllowedPattern: "[a-z]+"
  CidrPrefix:
    Description: IPv4 CIDR block prefix (e.g. 10.10, 172.16 etc...)
    Type: String
    Default: 172.16
  ComposerName:
    Type: String
  ProviderName:
    Type: String
  InteractiveClusterName:
    Type: String


Resources:

  CloudFormationPackageS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub "${ResourcePrefix}-${EnvironmentName}-cloudformation-scripts"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  CodeBuildRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - "sts:AssumeRole"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Effect: Allow
        Version: 2012-10-17
      Description: Grant AWS services access to Code Build
      Path: /
      Policies:
        - PolicyName: !Sub ${ResourcePrefix}-${EnvironmentName}-code-build-admin-access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action: "*"
                Effect: Allow
                Resource: "*"
      RoleName: !Sub "${ResourcePrefix}-${EnvironmentName}-code-build-role"

  InfrastructureCodeBuild:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Description: Infrastructure CloudFormation Build & Packaging
      SourceVersion: !Ref GitHubBranch
      Source:
        BuildSpec: buildspec/config.yml
        Auth:
          Type: CODECONNECTIONS
          Resource: !Ref CodeStarConnectionArn
        Location: !Sub https://github.com/KaishveTatva/interactive.believe.co.git
        ReportBuildStatus: true
        Type: GITHUB
      Name: !Sub ${ResourcePrefix}-${EnvironmentName}-infrastructure
      Artifacts:
        Type: NO_ARTIFACTS
      ServiceRole: !Ref CodeBuildRole
      QueuedTimeoutInMinutes: 30
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Ref LogsInfrastructureCodeBuild
          Status: "ENABLED"
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux-x86_64-standard:5.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: EnvironmentName
            Type: PLAINTEXT
            Value: !Ref EnvironmentName
          - Name: ResourcePrefix
            Type: PLAINTEXT
            Value: !Ref ResourcePrefix
          - Name: S3_Bucket
            Type: PLAINTEXT
            Value: !Ref CloudFormationPackageS3Bucket
          - Name: CidrPrefix
            Type: PLAINTEXT
            Value: !Ref CidrPrefix
          - Name: ComposerName
            Type: PLAINTEXT
            Value: !Ref ComposerName
          - Name: ProviderName
            Type: PLAINTEXT
            Value: !Ref ProviderName
          - Name: InteractiveClusterName
            Type: PLAINTEXT
            Value: !Ref InteractiveClusterName
          
      TimeoutInMinutes: 15

  LogsInfrastructureCodeBuild:
    Type: "AWS::Logs::LogGroup"
    Properties:
      RetentionInDays: 365
      LogGroupName: !Sub "code-build-${ResourcePrefix}-${EnvironmentName}-infrastructure"
