AWSTemplateFormatVersion: 2010-09-09
Description: Creates CloudFront distribution, and Route 53 DNS record pointing to the bucket

# -- Parameters Definition -- #
Parameters:
  ResourcePrefix:
    Description: Resource prefix that will be used for all resource names (e.g. emsp-vpc)
    Type: String
  EnvironmentName:
    Description: Environment name that will be used for resource names
    Type: String
  DomainName:
    Type: String
    Description: The DNS name of an existing Amazon Route 53 hosted zone.
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: Must be a valid DNS zone name.
  SubDomainName:
    Type: String
    Description: The DNS name of an existing Amazon Route 53 hosted zone.
  UIDomainName:
    Type: String
    Description: The DNS name of an existing Amazon Route 53 hosted zone.
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: Must be a valid DNS zone name.
  S3UIDomainName:
    Type: String
    Description: The DNS name of an existing Amazon Route 53 hosted zone.
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: Must be a valid DNS zone name.
  CertificateArn:
    Type: String
    Description: The Amazon Resource Name (ARN) of an AWS Certificate Manager (ACM) certificate.
    AllowedPattern: 'arn:aws:acm:.*'
  BucketArn:
    Type: String
    Description: The Amazon Resource Name (ARN) of an S3 website bucket.
    AllowedPattern: 'arn:aws:s3:.*'
  BucketDomainName:
    Type: String
  WebsiteLabel:
    Type: String 
    Description: Website label
  WebACLARN:
    Type: String
    Description: WAF global ACL Arn for CloudFront
    Default: "arn:aws:wafv2:not-confugured"
    AllowedPattern: 'arn:aws:wafv2:.*'
  WAFCloudfrontEnabled:
    Type: String
    Description: Enable WAF (Web Application Firewall) for CloudFront
    AllowedValues:
      - true
      - false
Conditions:
  IsProductionEnvironment: !Equals [!Ref EnvironmentName, "prod"]
  IsStagingEnvironment: !Equals [!Ref EnvironmentName, "staging"]
  ProvisionWAFCloudfront: !Equals [!Ref WAFCloudfrontEnabled, true]
# -- Resources Definition -- #
Resources: 
  CloudFrontDistribution:
    DependsOn: CloudFrontOriginAccessControl
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        WebACLId: !If
          - ProvisionWAFCloudfront
          - !Ref WebACLARN
          - !Ref "AWS::NoValue"
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
        ViewerCertificate:
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-viewercertificate.html
# If the distribution uses Aliases (alternate domain names or CNAMEs) and 
# the SSL/TLS certificate is stored in AWS Certificate Manager (ACM), 
# provide the Amazon Resource Name (ARN) of the ACM certificate. 
# CloudFront only supports ACM certificates in the US East (N. Virginia) Region (us-east-1).
          AcmCertificateArn: !Ref CertificateArn
          MinimumProtocolVersion: TLSv1.2_2019
          SslSupportMethod: sni-only
        Aliases:
          - !Ref UIDomainName
        DefaultCacheBehavior:
          AllowedMethods: 
            - HEAD
            - GET
          CachedMethods:
            - HEAD
            - GET
          Compress: true
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          MinTTL: 1296000
          DefaultTTL: 31536000
          MaxTTL: 31536000
          TargetOriginId: frontendSite
          ViewerProtocolPolicy: redirect-to-https
        CacheBehaviors:
          - PathPattern: /static/*
            TargetOriginId: frontendSite
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - HEAD
              - GET
            CachedMethods:
              - HEAD
              - GET
            Compress: true
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            MinTTL: 31536000
            DefaultTTL: 31536000
            MaxTTL: 31536000
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        # IPV6Enabled: true | false
        Origins:
          - DomainName: !Ref BucketDomainName
            Id: frontendSite
            S3OriginConfig:
              OriginAccessIdentity: ""
            OriginAccessControlId: !Ref CloudFrontOriginAccessControl
      Tags:
        - Key: Name
          Value: !Sub "${ResourcePrefix}-${EnvironmentName}-${SubDomainName}-cf"
        - Key: interactive:instance
          Value: !Sub ${ResourcePrefix}-${EnvironmentName}
        - Key: interactive:criticality
          Value: !If
            - IsProductionEnvironment
            - "Teir 1"
            - !If
              - IsStagingEnvironment
              - "Teir 2"
              - "Teir 3"
        - Key: interactive:environment
          Value: !Ref EnvironmentName
        - Key: interactive:object-type
          Value: CloudFront Distribution

  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties: 
      OriginAccessControlConfig:
          Description: !Sub Origin Access Control for ${BucketDomainName}
          Name: !Ref BucketDomainName
          OriginAccessControlOriginType: s3
          SigningBehavior: always
          SigningProtocol: sigv4

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html
  # For CloudFront distribution, Z2FDTNDATAQYW2
  UIRoute53RecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneName: !If 
        - IsProductionEnvironment
        - !Sub "${DomainName}."
        - !Sub "${EnvironmentName}.${DomainName}."
      Name: !Sub "${UIDomainName}."
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName
  
  UIBucketPolicyCloudFrontRead:
    DependsOn: CloudFrontDistribution
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3UIDomainName
      PolicyDocument:
        Id: 'CloudFrontWebsiteBucketReadAccessPolicy'
        Version: '2012-10-17'
        Statement:
          - Sid: "AllowCloudFrontServicePrincipal"
            Effect: "Allow"
            Principal:
              Service: "cloudfront.amazonaws.com"
            Action: "s3:GetObject"
            Resource: 
              - !Sub "${BucketArn}/*"
              - !Sub "${BucketArn}"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

  SSMDistributionID:
    Type: "AWS::SSM::Parameter"
    Properties:
      Type: String
      Description: CDN Distribution ID
      Value: !Ref CloudFrontDistribution
      Name: !Sub "/${ResourcePrefix}/${EnvironmentName}/${WebsiteLabel}/distribution/id"

  SSMUIURL:
    Type: "AWS::SSM::Parameter"
    Properties:
      Type: String
      Description: UI URL
      Value: !Sub https://${UIDomainName}
      Name: !Sub "/${ResourcePrefix}/${EnvironmentName}/${WebsiteLabel}/url"
