AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template To Create a DynamoDB

Parameters:
  ResourcePrefix:
    Description: Resource prefix that will be used for all resource names (e.g. CPO-s3)
    Type: String
  EnvironmentName:
    Description: An environment name that will be used for resource names
    Type: String
  TableName:
    Type: String
  HashKeyElementName1:
    Type: String
    Description: Hash Key Name
  HashKeyElementName2:
    Type: String
    Description: Hash Key Name
  HashKeyElementType:
    Type: String
    Default: S
    Description: Hash Key Type
  DeletionPolicy:
    Type: String
    Description: Deletion Policy for Dynamo DB
  AttributeName:
    Type: String

Mappings:
  Criticality:
    prod:
      Tier: "Tier 1"
    staging:
      Tier: "Tier 2"
    uat:
      Tier: "Tier 2"
    maint:
      Tier: "Tier 2"  
    dev:
      Tier: "Tier 3"
    qa:
      Tier: "Tier 3"
    infra:
      Tier: "Tier 3"

Conditions:
  WebsocketDynamoDB:
    Fn::Equals:
      - Ref: TableName
      - "ws-connections"
  NotWebsocketDynamoDB: !Not [!Equals [!Ref TableName, 'ws-connections']]

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${ResourcePrefix}-${EnvironmentName}-${TableName}
      DeletionProtectionEnabled: !Ref DeletionPolicy
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: !Ref HashKeyElementName1
          AttributeType: !Ref HashKeyElementType
        - AttributeName: !Ref HashKeyElementName2
          AttributeType: S
        - !If 
          - NotWebsocketDynamoDB
          - AttributeName: !Ref AttributeName
            AttributeType: S
          - !Ref "AWS::NoValue"
      KeySchema:
        - AttributeName: !Ref HashKeyElementName1
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: !Sub ${ResourcePrefix}-${EnvironmentName}-index
          KeySchema:
            - AttributeName: !Ref HashKeyElementName2
              KeyType: HASH 
          Projection:
            ProjectionType: ALL
        - !If 
          - NotWebsocketDynamoDB
          - IndexName: !Sub ${ResourcePrefix}-${EnvironmentName}-index2
            KeySchema:
              - AttributeName: !Ref AttributeName
                KeyType: HASH  
            Projection:
              ProjectionType: ALL
          - !Ref "AWS::NoValue"
      Tags:
        - Key: Name
          Value: !Sub ${ResourcePrefix}-${EnvironmentName}-${TableName}
        - Key: iv:product
          Value: CPO
        - Key: iv:application
          Value: CPO
        - Key: iv:instance
          Value: !Sub ${ResourcePrefix}-${EnvironmentName}
        - Key: iv:owner
          Value: InstaVolt UK
        - Key: iv:criticality
          Value: !FindInMap [Criticality, !Ref EnvironmentName, Tier]
        - Key: iv:updated-in-release
          Value: "R1.1.0"
        - Key: iv:environment
          Value: !Ref EnvironmentName
        - Key: iv:country
          Value: !Sub "${AWS::Region}"
        - Key: iv:object-type
          Value: DynamoDB Table

  SSMForDynamoDBTable:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Type: String
      Description: 'Dynamo DB table name'
      Value: !Ref DynamoDBTable
      Name: !Sub '/${ResourcePrefix}/${EnvironmentName}/${TableName}/name'
      Tags:
        Name: !Sub /${ResourcePrefix}/${EnvironmentName}/${TableName}/name
        iv:product: CPO
        iv:application: CPO
        iv:instance: !Sub ${ResourcePrefix}-${EnvironmentName}
        iv:owner: InstaVolt UK
        iv:updated-in-release: "R1.1.0"
        iv:criticality: !FindInMap [Criticality, !Ref EnvironmentName, Tier]
        iv:environment: !Ref EnvironmentName
        iv:country: !Sub "${AWS::Region}"
        iv:object-type: SSM Parameter
