AWSTemplateFormatVersion: 2010-09-09
Description: To create ECS Clusters and Service.

Parameters:
  ResourcePrefix:
    Description: Resource prefix that will be used for all resource names (e.g. CPO-s3)
    Type: String
  EnvironmentName:
    Description: An environment name that will be used for resource names
    Type: String
  ClusterName:
    Description: An environment name that will be used for resource names
    Type: String
    
Mappings:
  Criticality:
    prod:
      Tier: "Tier 1"
    staging:
      Tier: "Tier 2"
    uat:
      Tier: "Tier 2"
    maint:
      Tier: "Tier 2"  
    dev:
      Tier: "Tier 3"
    qa:
      Tier: "Tier 3"
    infra:
      Tier: "Tier 3"

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${ResourcePrefix}-${EnvironmentName}-${ClusterName}
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
        - CapacityProvider: FARGATE_SPOT
          Weight: 1
      Tags:
        - Key: Name
          Value: !Sub ${ResourcePrefix}-${EnvironmentName}-${ClusterName}
        - Key: iv:product
          Value: CPO
        - Key: iv:application
          Value: CPO
        - Key: iv:instance
          Value: !Sub ${ResourcePrefix}-${EnvironmentName}
        - Key: iv:owner
          Value: InstaVolt UK
        - Key: iv:criticality
          Value: !FindInMap [Criticality, !Ref EnvironmentName, Tier]
        - Key: iv:updated-in-release
          Value: "R1.1.0"
        - Key: iv:environment
          Value: !Ref EnvironmentName
        - Key: iv:country
          Value: !Sub "${AWS::Region}"
        - Key: iv:object-type
          Value: ECS Cluster
  
  SSMforECSClusterName:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Type: String
      Description: !Sub 'Name of ${ClusterName} ECS Cluster'
      Value: !Sub ${ResourcePrefix}-${EnvironmentName}-${ClusterName}
      Name: !Sub '/${ResourcePrefix}/${EnvironmentName}/${ClusterName}/name'
      Tags:
        Name: !Sub /${ResourcePrefix}/${EnvironmentName}/${ClusterName}/name
        iv:product: CPO
        iv:application: CPO
        iv:instance: !Sub ${ResourcePrefix}-${EnvironmentName}
        iv:owner: InstaVolt UK
        iv:updated-in-release: "R1.1.0"
        iv:criticality: !FindInMap [Criticality, !Ref EnvironmentName, Tier]
        iv:environment: !Ref EnvironmentName
        iv:country: !Sub "${AWS::Region}"
        iv:object-type: SSM Parameter
    
  SSMforECSClusterArn:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Type: String
      Description: !Sub 'ARN of ${ClusterName} ECS Cluster'
      Value: !GetAtt ECSCluster.Arn
      Name: !Sub '/${ResourcePrefix}/${EnvironmentName}/cluster/${ClusterName}/arn'
      Tags:
        Name: !Sub /${ResourcePrefix}/${EnvironmentName}/cluster/${ClusterName}/arn
        iv:product: CPO
        iv:application: CPO
        iv:instance: !Sub ${ResourcePrefix}-${EnvironmentName}
        iv:owner: InstaVolt UK
        iv:updated-in-release: "R1.1.0"
        iv:criticality: !FindInMap [Criticality, !Ref EnvironmentName, Tier]
        iv:environment: !Ref EnvironmentName
        iv:country: !Sub "${AWS::Region}"
        iv:object-type: SSM Parameter
     
Outputs:
  ClusterName:
    Description: ECR Cluster Name
    Value: !Ref ECSCluster

  ClusterArn:
    Description: ECR Cluster ARN
    Value: !GetAtt ECSCluster.Arn
