AWSTemplateFormatVersion: 2010-09-09
Description: To create ECS Clusters and Service.

Parameters:
  ResourcePrefix:
    Description: Resource prefix that will be used for all resource names (e.g. CPO-s3)
    Type: String
  EnvironmentName:
    Description: An environment name that will be used for resource names
    Type: String
  VpcId:
    Description: Select the VPC where ECS services will be deployed.
    Type: AWS::EC2::VPC::Id
  ServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow internal traffic
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !Ref ServiceSecurityGroup