AWSTemplateFormatVersion: 2010-09-09
Description: Network Infrastructure - VPC

# -- Parameters Definition -- #
Parameters:
  ResourcePrefix:
    Description: Resource prefix that will be used for all resource names (e.g. emsp-vpc)
    Type: String
  EnvironmentName:
    Description: Environment name that will be used for resource names
    Type: String
  CidrBlock:
    Description: The primary IPv4 CIDR block for the VPC
    Type: String
Conditions:
  IsProductionEnvironment: !Equals [!Ref EnvironmentName, "prod"]
  IsStagingEnvironment: !Equals [!Ref EnvironmentName, "staging"]

# -- Resources Definition -- #
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${ResourcePrefix}-${EnvironmentName}-VPC
        - Key: interactive:instance
          Value: !Sub ${ResourcePrefix}-${EnvironmentName}
        - Key: interactive:criticality
          Value: !If
            - IsProductionEnvironment
            - "Teir 1"
            - !If
              - IsStagingEnvironment
              - "Teir 2"
              - "Teir 3"
        - Key: interactive:environment
          Value: !Ref EnvironmentName
        - Key: interactive:object-type
          Value: EC2 VPC
  
  SSMVpcId:
    Type: AWS::SSM::Parameter
    Properties:
      Description: VPC Id
      Type: String
      Name: !Sub "/${ResourcePrefix}/${EnvironmentName}/vpc-id"
      Value: !Ref VPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${ResourcePrefix}-${EnvironmentName}-IGW
        - Key: interactive:instance
          Value: !Sub ${ResourcePrefix}-${EnvironmentName}
        - Key: interactive:criticality
          Value: !If
            - IsProductionEnvironment
            - "Teir 1"
            - !If
              - IsStagingEnvironment
              - "Teir 2"
              - "Teir 3"
        - Key: interactive:environment
          Value: !Ref EnvironmentName
        - Key: interactive:object-type
          Value: EC2 InternetGateway
  
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  VPCFlowLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub "${ResourcePrefix}-${EnvironmentName}-vpc-flow-LogGroup"
      RetentionInDays: 365
      Tags:
        - Key: Name
          Value: !Sub ${ResourcePrefix}-${EnvironmentName}-vpc-flow-LogGroup
        - Key: interactive:instance
          Value: !Sub ${ResourcePrefix}-${EnvironmentName}
        - Key: interactive:criticality
          Value: !If
            - IsProductionEnvironment
            - "Teir 1"
            - !If
              - IsStagingEnvironment
              - "Teir 2"
              - "Teir 3"
        - Key: interactive:environment
          Value: !Ref EnvironmentName
        - Key: interactive:object-type
          Value: Logs LogGroup

  VPCFlowLogRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub ${ResourcePrefix}-${EnvironmentName}-vpc-flow-log-role
      Path: "/"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: 'vpc-flow-logs.amazonaws.com'
          Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
      Tags:
        - Key: Name
          Value: !Sub ${ResourcePrefix}-${EnvironmentName}-vpc-flow-log-role
        - Key: interactive:instance
          Value: !Sub ${ResourcePrefix}-${EnvironmentName}
        - Key: interactive:criticality
          Value: !If
            - IsProductionEnvironment
            - "Teir 1"
            - !If
              - IsStagingEnvironment
              - "Teir 2"
              - "Teir 3"
        - Key: interactive:environment
          Value: !Ref EnvironmentName
        - Key: interactive:object-type
          Value: IAM Role

  VPCFlowLog:
    Type: 'AWS::EC2::FlowLog'
    Properties:
      DeliverLogsPermissionArn: !GetAtt 'VPCFlowLogRole.Arn'
      LogGroupName: !Ref VPCFlowLogGroup
      ResourceId: !Ref VPC
      ResourceType: 'VPC'
      TrafficType: 'REJECT'
      Tags:
        - Key: Name
          Value: !Sub ${ResourcePrefix}-${EnvironmentName}-vpc-flow-log
        - Key: interactive:instance
          Value: !Sub ${ResourcePrefix}-${EnvironmentName}
        - Key: interactive:criticality
          Value: !If
            - IsProductionEnvironment
            - "Teir 1"
            - !If
              - IsStagingEnvironment
              - "Teir 2"
              - "Teir 3"
        - Key: interactive:environment
          Value: !Ref EnvironmentName
        - Key: interactive:object-type
          Value: EC2 FlowLog

# -- Outputs -- #
Outputs:
  CidrBlock:
    Description: The primary IPv4 CIDR block of the VPC.
    Value: !Ref CidrBlock
  VpcId:
    Value: !Ref VPC
    Description: The VPC unique identifier.
  IGWId:
    Value: !Ref InternetGateway
    Description: The InternetGateway unique identifier.