AWSTemplateFormatVersion: 2010-09-09
Description: Creates an S3 bucket for hosting a static website

# -- Parameters Definition -- #
Parameters:
  ResourcePrefix:
    Description: Resource prefix that will be used for all resource names (e.g. emsp-vpc)
    Type: String
  EnvironmentName:
    Description: Environment name that will be used for resource names
    Type: String
  DomainName:
    Type: String
    Description: The DNS name of an existing Amazon Route 53 hosted zone
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: Must be a valid DNS zone name
  SubDomainName:
    Description: Frontend Sub Domain Name like ui, apps
    Type: String 
  AllowOrigin:
    Description: FrontEnd Access URL
    Type: List<String>    
  WebsiteLabel:
    Type: String 
    Description: Website label
  UniqueSubstring:
    Type: String
    Description: An unique name for s3 bucket.
    Default: ""
    AllowedPattern: "(^$|^[a-z0-9][a-z0-9.-]*[a-z0-9]$)"

Conditions:
  IsUniqueSubstringEmpty: !Equals [!Ref UniqueSubstring, ""]
  IsProductionEnvironment: !Equals [!Ref EnvironmentName, "prod"]
  IsStagingEnvironment: !Equals [!Ref EnvironmentName, "staging"]

# -- Resources Definition -- #
Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties: 
      # AccessControl: PublicRead
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketName:
        !If
          - IsUniqueSubstringEmpty
          - !Sub "${WebsiteLabel}.${EnvironmentName}.${DomainName}"
          - !Sub "${ResourcePrefix}-${EnvironmentName}-${WebsiteLabel}-website-${UniqueSubstring}"
      BucketEncryption:
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
            AllowedOrigins: !Ref AllowOrigin
      Tags:
        - Key: Name
          Value: !If
          - IsUniqueSubstringEmpty
          - !Sub "${WebsiteLabel}.${EnvironmentName}.${DomainName}"
          - !Sub "${ResourcePrefix}-${EnvironmentName}-${WebsiteLabel}-website-${UniqueSubstring}"
        - Key: interactive:instance
          Value: !Sub ${ResourcePrefix}-${EnvironmentName}
        - Key: interactive:criticality
          Value: !If
            - IsProductionEnvironment
            - "Teir 1"
            - !If
              - IsStagingEnvironment
              - "Teir 2"
              - "Teir 3"
        - Key: interactive:environment
          Value: !Ref EnvironmentName
        - Key: interactive:object-type
          Value: S3 Bucket

  SSMUIBucket:
    Type: "AWS::SSM::Parameter"
    Properties:
      Type: String
      Name: !Sub "/${ResourcePrefix}/${EnvironmentName}/s3/${WebsiteLabel}"
      Value:
        !If
          - IsUniqueSubstringEmpty
          - !Sub "${WebsiteLabel}.${EnvironmentName}.${DomainName}"
          - !Sub "${ResourcePrefix}-${EnvironmentName}-${WebsiteLabel}-website-${UniqueSubstring}"
      Description: "Name of UI S3 Bucket"

Outputs:
  BucketDomainName:
    Value: !GetAtt WebsiteBucket.DomainName
    Description: Website's Public S3 URL
  BucketArn:
    Description: Website's Bucket Arn
    Value: !GetAtt WebsiteBucket.Arn